root: true
env:
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  dot-notation: error
  eqeqeq: error
  indent:
  - error
  - 4
  linebreak-style:
  - error
  - unix
  no-bitwise: error
  no-caller: error
  no-console: off
  no-extend-native: error
  no-native-reassign: error
  no-new: error
  no-shadow-restricted-names: error
  no-sequences: error
  no-unused-expressions: error
  no-use-before-define:
  - error
  - functions: false
    classes: false
  quotes:
  - error
  - single
  - avoid-escape
  semi:
  - error
  - always
  space-before-function-paren:
  - error
  - anonymous: always
    named: never
extends: "eslint:recommended"
